experiment_name: centerpoint_nus_activations
experiment_path: ./
device: cuda:0
method: activations
verbose: True
detection:
  device: 'cuda:1'
  dataset:
    name: NuScenesDataset
    root_dir: /media/ssd_reza/nuscenes
    version: v1.0-trainval
    process: True
    save_path: "/media/wmg-5gcat/Co-op Autonomy 2/Hakan/"
    save_filename: nuscenes_train_fix.pkl
    filtering_style: FilterType.ELLIPSE
    filter_params:
      a: 15
      b: 25
      offset: -10
      axis: 1
  model:
    name: centerpoint
    root_dir: /mnt/ssd2/mmdetection3d/
    config_dir: configs/
    checkpoint_dir: ckpts/
    config : centerpoint_voxel0075_second_secfpn_head-dcn-circlenms_8xb4-cyclic-20e_nus-3d.py #pointpillars_hv_secfpn_sbn-all_8xb2-amp-2x_nus-3d.py
    checkpoint: centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus_20220810_025930-657f67e0.pth #hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d_20201020_222626-c3f0483e.pth
  #save_path: ./custom_dataset/
  training_params: {}
extraction:
  active: True
  device: 'cuda:0'
  labels_only: True
  object_filter: True
  sparse: True
  score_threshold: 0.5
  split: 'test'
  dataset:
    name: NuScenesDataset
    root_dir: /media/ssd_reza/nuscenes/
    version: v1.0-trainval
    process: False
    filter_labels_only: False
    save_path: "/media/wmg-5gcat/Co-op Autonomy 2/Hakan/"
    save_filename: nuscenes_train_fix.pkl
    filtering_style: FilterType.ELLIPSE
    filter_params:
      a: 15
      b: 25
      offset: -10
      axis: 1
  model:
    name: centerpoint
    root_dir: /home/wmg-5gcat/Desktop/Sajjad/DistEstIntrospection/mmdetection3d
    config_dir: configs/
    checkpoint_dir: ckpts/
    config : centerpoint_voxel0075_second_secfpn_head-dcn-circlenms_8xb4-cyclic-20e_nus-3d.py #pointpillars_hv_secfpn_sbn-all_8xb2-amp-2x_nus-3d.py
    checkpoint: centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus_20220810_025930-657f67e0.pth #hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d_20201020_222626-c3f0483e.pth
  method:
    name: raw_activations
    hook:
      layer: pts_backbone.blocks #pts_backbone
      indexes: [0,0,1]
      extract_from: [0,1,1]
      layer_index: 1
    save_dir: ../custom_dataset/nus_centerpoint_activations_filtered_objects/
    labels_file_name: nus_centerpoint_labels_filtered_objects.csv
    balanced: False
    transforms: None
    extension: .pcd.bin
    save_input: False
    #Are theese needed?
    # config : /mnt/ssd2/mmdetection3d/configs/pointpillars/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d.py
    # checkpoint:  /mnt/ssd2/mmdetection3d/ckpts/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d_20201020_222626-c3f0483e.pth
  save_path: ./custom_dataset/
  training_params: {}
# experiment_name: point_pillar_nus_activations
# Only showing the introspection section for brevity
introspection:
  experiment_name: nus_centerpoint_filtered_spatial_early_wobjf
  wandb:
    is_sweep: False
    sweep_configuration:
      method: bayes
      name: nus_centerpoint_filtered_spatial_early_wobjf
      metric:
        name: val_loss
        goal: minimize
      parameters:
        model_yaml:
          values:
          - configs/networks/resnet18_fcn.yaml
          # - configs/networks/attention_resnet18_fcn.yaml
        optimizer:
          values:
          - SGD
          # - Adam
        criterion:
          values:
          - FocalLoss
        lr:
          values:
          # - 0.005
          - 0.001
          - 0.01
        batch_size:
          values:
          # - 16
          - 256
        gamma:
          values:
          - 5
          # - 0
          # - 2
    project: introspect3D
    entity: yatbazhakan
    mode: online
    name: nus_centerpoint_filtered_wobjf_early
  verbose: True
  method:
    task: multiclass
    clip_grad: 1.0
    log_grads: True
    cross_validation:
      type: None
      iteration: 1
      balanced: false
      train_test_split: 0.2
      validation_split: 0.2
    processing:
      active: True
      method: ProcessorEnum.RAW
      stack: True
      params:
        # config:
        #   percentile: 0.9
        #   method: p
        config:
          functions:
            - mean
            - max
            - std
    model:
      layer_config: configs/networks/resnet18_fcn.yaml
    optimizer:
      type: SGD
      params: 
        lr: 0.1
        weight_decay: 0.001
    criterion:
      type: FocalLoss
      params:
        reduction: sum
        gamma: 5
        weight:
        - 0.78
        - 1.39
    scheduler:
      type: ReduceLROnPlateau
      params:
        patience : 15
        factor: 0.7
    epochs: 200
    log_interval: 1
    save_interval: 1
    early_stop: 20
    sanity_check: false
    save_path: outputs/ckpts
    save_name: nus_centerpoint_filtered_spatial_early_wobjf.pt
  device: cuda:0
  filtering: none
  dataset:
    name: ActivationDataset
    config:
      root_dir: "/media/wmg-5gcat/Co-op Autonomy 2/Hakan/custom_dataset/nus_centerpoint_activations_filtered_objects"  
      label_file: nus_centerpoint_labels_filtered_objects.csv
      classes: ['No Error', 'Error']
      label_field: is_missed
      layer: 0
      is_multi_feature: False
      is_sparse: True
      extension: .pt
      name: nuscenes
  dataloader:
    all:
      batch_size: 128
      shuffle: True
    train:
      batch_size: 128
      shuffle: True
    test:
      batch_size: 1
      shuffle: False
  operation: 
    type: traineval
    load_model: False
