layers:  
  - type: "Conv3DBlock"
    params:
      in_channels: 1
      out_channels: 32
      kernel_size: 3
  - type: "MaxPool3d"
    params:
      kernel_size: 2
      stride: 2
  - type: "Conv3DBlock"
    params:
      in_channels: 32
      out_channels: 64
      kernel_size: 3
  - type: "MaxPool3d"
    params:
      kernel_size: 2
      stride: 2
  - type: "Conv3DBlock"
    params:
      in_channels: 64
      out_channels: 64
      kernel_size: 3
  - type: "MaxPool3d"
    params:
      kernel_size: 2
      stride: 2
  - type: "Flatten"
    params: {}

  - type: "Linear"
    params:
      in_features: 86016
      out_features: 4096
  - type: "Dropout"
    params:
      p: 0.5
  - type: "Linear"
    params:
      in_features: 4096
      out_features: 1024
  - type: "Dropout"
    params:
      p: 0.5
  - type: "Linear"
    params:
      in_features: 1024
      out_features: 256
  - type: "Dropout"
    params:
      p: 0.3
  - type: "Linear"
    params:
      in_features: 256
      out_features: 128
  - type: "Dropout"
    params:
      p: 0.3
  - type: "Linear"
    params:
      in_features: 128
      out_features: 2