layers: 
  - type: "BasicConvBlock"
    params:
      in_channels: 256  # Adjust according to input channels
      out_channels: 128
      kernel_size: 3
      stride: 1
      padding: 1

  - type: "InceptionBlock"
    params:
      in_channels: 128

  - type: "BasicConvBlock"
    params:
      in_channels: 256  # Adjust according to input channels
      out_channels: 128
      kernel_size: 3
      stride: 1
      padding: 1

  - type: "DilatedConvBlock"
    params:
      in_channels: 128
      out_channels: 64
      dilation: 2

  - type: "Conv2d"
    params:
      in_channels: 64
      out_channels: 2  # Adjust according to the number of classes
      kernel_size: 1
      stride: 1
      padding: 0

  - type: "AdaptiveAvgPool2d"
    params:
      output_size: 1

  - type: "Flatten"
    params: {}
