layers:
  - type: "Linear"
    params:
      in_features: 768
      out_features: 256
  - type: "Dropout"
    params:
      p: 0.3
  - type: "Linear"
    params:
      in_features: 256
      out_features: 128
  - type: "Dropout"
    params:
      p: 0.3
  - type: "Linear"
    params:
      in_features: 128
      out_features: 2