layers:
  - type: "GCNConv"
    params:
      in_channels: 4 # Input feature dimension per node
      out_channels: 64 # Arbitrary, intermediate feature dimension
  - type: "ReLU"
    params: {}
  - type: "GCNConv"
    params:
      in_channels: 64 # Must match the output of the previous GraphConv layer
      out_channels: 768 # Matching your required input for the first linear layer
  - type: "ReLU"
    params: {}
  - type: "Linear"
    params:
      in_features: 768
      out_features: 256
  - type: "ReLU"
    params: {}  
  - type: "Dropout"
    params:
      p: 0.3
  - type: "Linear"
    params:
      in_features: 256
      out_features: 128
  - type: "ReLU"
    params: {}
  - type: "Dropout"
    params:
      p: 0.3
  - type: "Linear"
    params:
      in_features: 128
      out_features: 2
