layers:
  # - type: ChannelAttention
  #   params:
  #     in_channels: 256
  - type: torchvision.models.resnet18
    in_channels: 64
    params:
      weights: ResNet18_Weights.IMAGENET1K_V1
  - type: "Flatten"
    params: {}
  # - type: "Linear"
  #   params:
  #     in_features: 2048
  #     out_features: 1024
  # - type: "Dropout"
  #   params:
  #     p: 0.5
  - type: "Linear"
    params:
      in_features: 1024
      out_features: 256
  - type: "Dropout"
    params:
      p: 0.5
  - type: "Linear"
    params:
      in_features: 256
      out_features: 128
  - type: "Dropout"
    params:
      p: 0.5
  - type: "Linear"
    params:
      in_features: 128
      out_features: 2