layers:
  - type: torchvision.models.resnet18
    in_channels: 256
    params:
      weights: ResNet18_Weights.IMAGENET1K_V1
  - type: "Flatten"
    params: {}
  - type: "Linear"
    params:
      in_features: 2048
      out_features: 512
  - type: "Dropout"
    params:
      p: 0.5
  - type: "ReLU"
    params: {}
  - type: "Linear"
    params:
      in_features: 512
      out_features: 2