layers:
  - type: torchvision.models.resnet18
    in_channels: 256
    params: {}
  - type: "Flatten"
    params: {}
  - type: "Linear"
    params:
      in_features: 2048
      out_features: 512
  - type: "ReLU"
    params: {}
  - type: "Dropout"
    params:
      p: 0.5
  - type: "Linear"
    params:
      in_features: 512
      out_features: 2
  # - type: "Dropout"
  #   params:
  #     p: 0.5
  # - type: "Linear"
  #   params:
  #     in_features: 256
  #     out_features: 128
  # - type: "Dropout"
  #   params:
  #     p: 0.5
  # - type: "Linear"
  #   params:
  #     in_features: 128
  #     out_features: 2