layers:
  - type: torchvision.models.resnet18
    in_channels: 2048
    params:
      weights: ResNet18_Weights.IMAGENET1K_V1
  # - type: "Flatten"
  #   params: {}
  # - type: "Linear"
  #   params:
  #     in_features: 2048
  #     out_features: 512
  - type: "Linear"
    params:
      in_features: 512
      out_features: 256
  - type: "Linear"
    params:
      in_features: 256
      out_features: 128
  - type: "Linear"
    params:
      in_features: 128
      out_features: 2