inp_shape: 
  channels: 256
  height: 90
  width: 90
layers: 
  - type: "CustomTransformerEncoder"
    params:
      embed_dim: 512
      num_heads: 8
      num_layers: 6
      C: 256
      H: 90
      W: 90