project_dir: D:/Introspect3D
datasets:
    - Kitti3D
    - Kitti2D
    - BDD100K
    - NuScenesDataset
    - ActivationDataset
    - CustomDataset
models: {}
operators:
  - ActivationExtractionOperator

