experiment_name: point_pillar_kitti_activations
experiment_path: ./
device: 'cuda:0'
method: activations
verbose: True
detection:
  device: 'cuda:0'
  dataset:
    name: Kitti
    root_dir: /mnt/ssd1/introspectionBase/datasets/KITTI/training/
    class_names: ['Car', 'Pedestrian', 'Cyclist']
    filtering_style: FilterType.NONE
  model:
    name: pointpillars
    root_dir: /mnt/ssd2/mmdetection3d/
    config_dir: configs/
    checkpoint_dir: ckpts/
    config: pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class.py
    checkpoint: hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth
  #save_path: ./custom_dataset/
  training_params: {}
extraction:
  active: True
  device: 'cuda:0'
  score_threshold: 0.5
  dataset:
    name: Kitti
    root_dir: /mnt/ssd2/kitti/training/
    class_names: ['Car', 'Pedestrian', 'Cyclist']
    filtering_style: FilterType.NONE
    filter_params:
      a: 25
      b: 15
      offset: -10
      axis: 0
  model:
    name: pointpillars
    root_dir: /mnt/ssd2/mmdetection3d/
    config_dir: configs/
    checkpoint_dir: ckpts/
    config: pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class.py
    checkpoint: hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth
  method:
    name: raw_activations
    hook:
      layer: backbone
      indexes: []
      layer_index: 2
    save_dir: ../custom_dataset/kitti_pointpillars_activations_raw/
    labels_file_name: kitti_point_pillars_labels_raw.csv
    balanced: False
    transforms: None
    # config: pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class.py
    # checkpoint: hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth
    extension: .bin
  #save_path: ./custom_dataset/
  training_params: {}
# experiment_name: point_pillar_kitti_activations
# Only showing the introspection section for brevity
introspection:
  experiment_name: point_pillar_kitti_activations
  wandb:
    is_sweep: False
    sweep_configuration: {}
    project: introspect3D
    entity: yatbazhakan
    mode: disabled
    name: point_pillar_kitti_scr_activations_all_multiclass
  verbose: True
  method:
    task: multiclass
    train_test_split: 0.2
    validation_split: 0.2
    processing:
      active: True
      method: ProcessorEnum.RAW
      params:
        config:
          grid_size: 16
        # config:
        #   percentile: 0.9
        #   method: p
        # config:
        #   functions:
        #     - mean
        #     - max
        #     - std
        # config:
        #   bins: 2000
    model: 
      layer_config: configs/networks/resnet18_fcn.yaml
    optimizer:
      type: SGD
      params: 
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.0001
    criterion:
      type: CrossEntropyLoss #BCEWithLogitsLoss
      params: {}
      #   weight: [0.78, 1.39]
    scheduler:
      type: ReduceLROnPlateau
      params:
        patience : 15
        factor: 0.7
    epochs: 100
    log_interval: 1
    save_interval: 1
    early_stop: 10
    sanity_check: False
    save_path: outputs/ckpts
    save_name: point_pillar_kitti_activations_raw_all_scr.pt
  device: cuda:0
  dataset:
    name: ActivationDataset
    config:
      root_dir: /mnt/ssd2/custom_dataset/kitti_pointpillars_activations_raw/
      label_file: kitti_point_pillars_labels_raw.csv
      classes: ['No Error', 'Error']
      name: kitti
  dataloader:
    all:
      batch_size: 32
      shuffle: True
    train:
      batch_size: 32
      shuffle: True
    test:
      batch_size: 1
      shuffle: False
  operation: 
    type: traineval
    load_model: True
