experiment_name: centerpoint_nus_activations
experiment_path: ./
device: 'cuda:0'
method: activations
verbose: True

detection:
  device: 'cuda:0'
  dataset:
    name: NuScenesDataset
    root_dir: /media/ssd_reza/nuscenes
    version: v1.0-trainval
    process: False
    save_path: /media/ssd_reza/nuscenes
    save_filename: nuscenes_train_lv.pkl
    filtering_style: FilterType.LEAD_VEHICLE
    filter_labels_only: True
    filter_params:
      width: 4
      length: 100
  model:
    name: centerpoint
    root_dir: /home/wmg-5gcat/Desktop/Sajjad/DistEstIntrospection/mmdetection3d
    config_dir: configs/
    checkpoint_dir: ckpts/
    config : centerpoint_voxel0075_second_secfpn_head-dcn-circlenms_8xb4-cyclic-20e_nus-3d.py #pointpillars_hv_secfpn_sbn-all_8xb2-amp-2x_nus-3d.py
    checkpoint: centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus_20220810_025930-657f67e0.pth #hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d_20201020_222626-c3f0483e.pth
  #save_path: ./custom_dataset/
  training_params: {}
extraction:
  active: True
  device: 'cuda:0'
  score_threshold: 0.5
  extract_labels_only: True
  dataset:
    name: NuScenesDataset
    root_dir: /media/ssd_reza/nuscenes
    version: v1.0-trainval
    process: False
    save_path: /media/ssd_reza/nuscenes
    save_filename: nuscenes_train_segment.pkl
    filter_object_classes: False
    filtering_style: FilterType.NONE
    filter_labels_only: False
    filter_params:
      width: 4
      length: 100
  model:
    name: centerpoint
    root_dir: /home/wmg-5gcat/Desktop/Sajjad/DistEstIntrospection/mmdetection3d
    config_dir: configs/
    checkpoint_dir: ckpts/
    config : centerpoint_voxel0075_second_secfpn_head-dcn-circlenms_8xb4-cyclic-20e_nus-3d.py #pointpillars_hv_secfpn_sbn-all_8xb2-amp-2x_nus-3d.py
    checkpoint: centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus_20220810_025930-657f67e0.pth #hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d_20201020_222626-c3f0483e.pth
  method:
    name: raw_activations
    label_image:
      width: 500
      height: 500
      resolution: 0.2
    hook:
      layer: pts_backbone.blocks #pts_backbone
      indexes: [0]
      extract_from: [0]
      layer_index: 1
    save_dir: /media/ssd_reza/sajjad/segment/nus_centerpoint_early_activations
    labels_file_name: nus_centerpoint_segment_labels.csv
    balanced: False
    transforms: None
    extension: .pcd.bin
    save_input: True
    #Are theese needed?
    # config : /mnt/ssd2/mmdetection3d/configs/pointpillars/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d.py
    # checkpoint:  /mnt/ssd2/mmdetection3d/ckpts/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d_20201020_222626-c3f0483e.pth
  save_path: ./custom_dataset/
  training_params: {}
# experiment_name: point_pillar_nus_activations
# Only showing the introspection section for brevity
introspection:
  experiment_name: centerpoint_nus_activations
  debug: False
  wandb:
    is_sweep: False
    sweep_configuration:
      method: grid
      name: None
      metric:
        name: val_loss
        goal: minimize
      parameters:
        model_yaml:
          values:
          #- configs/networks/resnet18_fcn_reg.yaml
           - configs/networks/resnet18_fcn_distmc.yaml
        optimizer:
          values:
          - SGD
        criterion:
          values:
          - FocalLoss
        lr:
          values:
          - 0.0005
          - 0.001
        batch_size:
          values:
          - 32
    project: DistEstimation
    entity: introspection_events
    mode: online
    name: None
  verbose: True
  method:
    task: binary
    cross_validation:
      type: holdout
      iteration: 1
      balanced: false
      train_test_split: 0.2
      validation_split: 0.2
    processing:
      active: True
      method: ProcessorEnum.RAW
      stack: False
      params:
        config:
        #   percentile: 0.9
        #   method: p
        config:
          functions:
            - mean
            - max
            - std
    model:
      layer_config: configs/networks/resnet18_fcn_distmc.yaml # fcn_only.yaml#
    optimizer:
      type: SGD
      params: 
        lr: 0.001 #0.0
        momentum: 0.9
        weight_decay: 0.001
    criterion:
      type: FocalLoss
      params:
        reduction: mean
        gamma: 5
    scheduler:
      type: ReduceLROnPlateau
      params:
        patience : 10
        factor: 0.7
    clip_grad:
      active: True
      value: 2
    epochs: 300
    log_interval: 1
    save_interval: 1
    early_stop: 50
    sanity_check: false
    save_path: outputs/ckpts
    save_name: centerpoint_nus_activations_raw_resnet_dist_mc.pt
  device: cuda:0
  filtering: none
  dataset:
    name: ActivationDataset
    config:
      root_dir: /media/ssd_reza/sajjad/distest/custom_dataset/nus_centerpoint_early_activations
      label_file: 'lv_dist_est2.csv'
      task: 'Classification'
      classes: ['Less_Than_0.1m', 'More_Than_0.1'] #['Less_Than_0.1m', 'Less_Than_2m', 'More_Than_2m']
      is_multi_feature: False
      extension: .npy
      name: nuscenes
  dataloader:
    all:
      batch_size: 32
      shuffle: True
      num_workers: 8
      pin_memory: False
    train:
      batch_size: 32
      shuffle: True
      num_workers: 8
      pin_memory: False
    test:
      batch_size: 32
      shuffle: False
      num_workers: 8
      pin_memory: False
  operation: 
    type: traineval #traineval #train # evaluate
    model_dir: 'outputs/ckpts/three_will_particular'
    load_model: False
